version: '3'
services:
  nginx:
    image: nginx:1.18
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./certbot_data:/letsencrypt
      - ./certbot_data/certs:/etc/letsencrypt      
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
  certbot:
    container_name: certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot_data:/letsencrypt
      - ./certbot_data/certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 13h & wait $${!}; done;'"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
